export const NotificationType = {
  // Actions
  ACTION_OVERDUE: 'ACTION_OVERDUE',
  ACTION_DUE_SOON: 'ACTION_DUE_SOON',
  ACTION_ASSIGNED: 'ACTION_ASSIGNED',
  ACTION_VALIDATED: 'ACTION_VALIDATED',
  ACTION_REOPENED: 'ACTION_REOPENED',
  ACTION_REJECTED: 'ACTION_REJECTED',
  // KPI (M1.6)
  KPI_THRESHOLD_CRITICAL: 'KPI_THRESHOLD_CRITICAL',
  KPI_THRESHOLD_WARNING: 'KPI_THRESHOLD_WARNING',
  KPI_NEGATIVE_TREND: 'KPI_NEGATIVE_TREND',
  // Validation Workflow (M1.6)
  VALIDATION_SUBMITTED: 'VALIDATION_SUBMITTED',
  VALIDATION_APPROVED: 'VALIDATION_APPROVED',
  VALIDATION_REJECTED: 'VALIDATION_REJECTED',
  VALIDATION_OVERDUE: 'VALIDATION_OVERDUE',
  // FIP (M1.6)
  FIP_VALIDITY_EXPIRING: 'FIP_VALIDITY_EXPIRING',
  FIP_VALIDITY_EXPIRED: 'FIP_VALIDITY_EXPIRED',
  // Document (M2)
  DOCUMENT_ACKNOWLEDGEMENT_REQUIRED: 'DOCUMENT_ACKNOWLEDGEMENT_REQUIRED',
  DOCUMENT_ACKNOWLEDGEMENT_REMINDER: 'DOCUMENT_ACKNOWLEDGEMENT_REMINDER',
  DOCUMENT_VALIDITY_EXPIRING: 'DOCUMENT_VALIDITY_EXPIRING',
  DOCUMENT_EXTERNAL_REVIEW_DUE: 'DOCUMENT_EXTERNAL_REVIEW_DUE',
  DOCUMENT_WORKFLOW_PENDING: 'DOCUMENT_WORKFLOW_PENDING',
  DOCUMENT_EXTERNAL_NORM_CHANGED: 'DOCUMENT_EXTERNAL_NORM_CHANGED',
} as const;

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType];

export const NOTIFICATION_TYPE_LABELS: Record<string, string> = {
  ACTION_OVERDUE: 'Action en retard',
  ACTION_DUE_SOON: 'Échéance proche',
  ACTION_ASSIGNED: 'Nouvelle action',
  ACTION_VALIDATED: 'Action validée',
  ACTION_REOPENED: 'Action rouverte',
  ACTION_REJECTED: 'Action refusée',
  KPI_THRESHOLD_CRITICAL: 'KPI zone critique',
  KPI_THRESHOLD_WARNING: 'KPI zone alerte',
  KPI_NEGATIVE_TREND: 'KPI tendance négative',
  VALIDATION_SUBMITTED: 'Validation soumise',
  VALIDATION_APPROVED: 'Validation approuvée',
  VALIDATION_REJECTED: 'Validation rejetée',
  VALIDATION_OVERDUE: 'Validation en retard',
  FIP_VALIDITY_EXPIRING: 'FIP expire bientôt',
  FIP_VALIDITY_EXPIRED: 'FIP expiré',
  DOCUMENT_ACKNOWLEDGEMENT_REQUIRED: 'Lecture obligatoire',
  DOCUMENT_ACKNOWLEDGEMENT_REMINDER: 'Relance lecture',
  DOCUMENT_VALIDITY_EXPIRING: 'Document expire bientôt',
  DOCUMENT_EXTERNAL_REVIEW_DUE: 'Revue doc externe',
  DOCUMENT_WORKFLOW_PENDING: 'Workflow en attente',
  DOCUMENT_EXTERNAL_NORM_CHANGED: 'Norme modifiée',
};
